### ISSUE TITLE
Name is too long

### ISSUE THREAD

**Issue by stevenvachon** [browserify/common-shakeify#15]
Should've been "shakeify". Browserify is already just commonjs, so the "common" is unnecessary.

**Comment by goto-bus-stop** [comment]
:woman_shrugging: it's a browserify plugin for `common-shake`.

**Comment by stevenvachon** [comment]
Not fair enough 😄

**Comment by goto-bus-stop** [comment]
i don't think it's worth the trouble of doing a rename and dealing with the confusion of having multiple versions of the same package on npm.
