### ISSUE TITLE
Bundle not tree-shaked even in the most simple use case

### ISSUE THREAD

**Issue by ericmorand** [browserify/common-shakeify#17]
Here is a super simple `package.js` script:

```
var iconv = require('iconv-lite');

console.warn('We are not using iconv at all!');
```

As you can see, iconv is never used.

Using the CLI command of the documentation `browserify -p [common-shakeify -v] package.js > bundle.js`, the final bundle is not tree-shaked. There is only one common-shake comment in the generated bundle:

`/* common-shake removed: exports.byteLength = */`

I expect the whole iconv module to be removed since it is not used at all.

**Comment by goto-bus-stop** [comment]
Yeah, common-shakeify only removes unused exports from modules. When building this my expectation was that a minifier like uglifyify could be used to remove modules that are entirely unused. But it's not entirely safe to totally remove require calls because they might change the global environment (eg polyfills), so minifiers don't touch it.

**Comment by goto-bus-stop** [comment]
I guess the expectation is that you don't include modules that you're not using in the first place, heh. Then common-shake can take care of the modules where you only use a small part.

**Comment by ericmorand** [comment]
> Yeah, common-shakeify only removes unused exports from modules.

That's what I assumed to. But there, basically all of the exports from `iconv `are unused.

> I guess the real expectation is that you don't include modules that you're not using in the first place, heh. 

In this case, what is the point of tree shaking? If I use a module for one of its functionnalities, I expect the others to be removed and their dependencies as well.

**Comment by goto-bus-stop** [comment]
If you use a few things from iconv-lite, the others should be removed. im not entirely sure how common-shake handles modules that are imported but unused entirely. Try using a small part of that module, if it doesn't use weird export patterns the rest should be dropped

**Comment by goto-bus-stop** [comment]
Oh actually iconv-lite aliases module.exports, which common-shake does not support.

**Comment by goto-bus-stop** [comment]
will close because the questions in this issue were settled, but opening a more specific issue for removing unused `require()` calls entirely here: https://github.com/browserify/common-shakeify/issues/28

thanks!
