### ISSUE TITLE
remove unused modules if they have sideEffects: false

### ISSUE THREAD

**Issue by goto-bus-stop** [browserify/common-shakeify#28]
Following from #17, although we can't remove unused modules in the general case, if something does

```js
var _ = require('lodash')
exports.a = function () { /* something not using lodash */ }
exports.b = function (x) { _.map(x, /* etc */) }
```
and you're not using `exports.b`, `exports.b` will be dropped, `lodash` becomes unused, and we can check the lodash package.json file to see that it is safe to remove the `require()` call.

So this is intended to address the case where all uses of a module have been shaken out, not for the case where it's not used in the first place—then it might be a polyfill or something.

**Comment by formula1** [comment]
Based off #17

I'm sure it would just add another thing on the todo list, but would it be possible to see if a file affects the window or global variable? Perhaps theres a way to ensure that the module is only exporting and not a polyfill. Big fan of browserify and how simple it is to use, want to see it at its best.
